### ISSUE TITLE
UI disolve not working for text in my scene

### ISSUE THREAD

**Issue by ghost** [mob-sakai/DissolveEffectForUGUI#12]
It works in demo scene provided but nothing happens when I move location up or down in game scene. I use standard text and unity 2018.2.0f2 on windows

**Comment by mob-sakai** [comment]
Hi @Magaknuto 

I had a mistake in the README!
In Unity5.6+, you should enable `TexCoord1` channel of canvas.

![](https://user-images.githubusercontent.com/12690315/46567584-3525f400-c970-11e8-9839-5c9e810b0b80.png)

**Comment by mob-sakai** [comment]
Currently, we do not develop in this repository.
DissolveEffectForUGUI was integrated into [UIEffect](https://github.com/mob-sakai/UIEffect).
![](https://user-images.githubusercontent.com/12690315/41398364-155cf5a6-6ff2-11e8-8124-9d16ef6ca267.gif)

If you are interested, please try UIEffect :smile:

**Comment by ghost** [comment]
ok thanks for feedback I will try it!!!
